apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsjourney-dev
  namespace: dev
  labels:
    app: devopsjourney
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsjourney
      environment: dev
  template:
    metadata:
      labels:
        app: devopsjourney
        environment: dev
    spec:
      containers:
      - name: container-app
        image: devopsjourney1/mywebapp:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: myconfigmapv1.0
       