apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.labels.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      environment: {{ .Values.labels.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        environment: {{ .Values.labels.environment }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
          name: {{ .Values.configMapName }}
        {{ if eq .Values.labels.environment "Production"}}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 50 milli cores (1/20 CPU)
          limits:
            memory: "128Mi" # 128 mebibytes 
            cpu: "100m"
        {{ end }}    